Generating visualizations...
C:\xampp\htdocs\klasifikasi-judul-skripsi\python-api\app.py:139: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(6, 5))
C:\xampp\htdocs\klasifikasi-judul-skripsi\python-api\venv\Lib\site-packages\sklearn\metrics\_plot\confusion_matrix.py:140: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, ax = plt.subplots()
Exception ignored in: <function Image.__del__ at 0x0000020C335E3C40>
Traceback (most recent call last):
  File "C:\Python313\Lib\tkinter\__init__.py", line 4242, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
